"""empty message

Revision ID: 655568074caf
Revises: 3cc7e902968c
Create Date: 2021-06-10 13:06:47.901361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655568074caf'
down_revision = '3cc7e902968c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
